### ISSUE TITLE
Change the way of installing photon

### ISSUE THREAD

**Issue by ragingwind** [react-photonkit/react-photonkit#1]
- npm install
- submodule of git
- download zip

**Comment by ragingwind** [comment]
I bet on npm

**Comment by ragingwind** [comment]
close as https://github.com/react-photonkit/react-photonkit/commit/47cff74b8b41bc774c41842593bf7dfd0a89d147 go NPM!

**Comment by importre** [comment]
:tulip:

**Comment by ragingwind** [comment]
https://github.com/react-photonkit/react-photonkit/commit/4bfeee423256efad4288724c3f1fdffc0f46b6a4

**Comment by ragingwind** [comment]
LGTM? https://github.com/react-photonkit/react-photonkit/commit/dd176d23dc8faacb399fc6fcc3203e0d365c62ef

**Comment by importre** [comment]
LGTM

**Comment by importre** [comment]
@ragingwind I've removed `photon` dir.

**Comment by ragingwind** [comment]
:+1:
