### ISSUE TITLE
Remove assets

### ISSUE THREAD

**Issue by ragingwind** [react-photonkit/react-photonkit#13]
For to be documentation, mostly like that use issue. see https://github.com/ragingwind/devdogs/issues/3

**Comment by importre** [comment]
:open_mouth: :bulb: :ok_hand: 

FYI: Currently I'm using only logo image. Uploaded here

![ic_launcher](https://cloud.githubusercontent.com/assets/1744446/10875790/af4cbbac-8179-11e5-851e-556c347c08bd.png)

**Comment by ragingwind** [comment]
:clap:
