### ISSUE TITLE
Cleanup released package

### ISSUE THREAD

**Issue by ragingwind** [react-photonkit/react-photonkit#2]
I think we have two options of exporting `dist` to NPM
1. Using npm script. Firstly, remove `dist` from repo and `dist` will be built during npm installing time
2. Using npm `files` in packages.json. Only released `dist` path except other sources

What's your think?

**Comment by importre** [comment]
:one: :+1:

**Comment by ragingwind** [comment]
:1234: :game_die:

**Comment by ragingwind** [comment]
:cry: We can't use option 1 cause that there are so many devDependencies. we wouldn't force developers to install webpack

**Comment by ragingwind** [comment]
See the changes of dist: https://github.com/react-photonkit/react-photonkit/commit/56b5e325c70759628eb9dc6b942a2e3cb3a6698a

```
node_modules
└── react-photonkit
    ├── dist
    ├── license
    ├── node_modules
    ├── package.json
    └── readme.md
```

Anything has been missing?

**Comment by importre** [comment]
https://github.com/react-photonkit/react-photonkit/issues/2#issuecomment-152544434: oh, misunderstood. you are right.

**Comment by importre** [comment]
https://github.com/react-photonkit/react-photonkit/issues/2#issuecomment-152547038:
what is `node_modules/node_modules`?

**Comment by ragingwind** [comment]
node_modules for react-photonkit

```
"classnames": "^2.1.5",
    "photon": "connors/photon#v0.1.2-alpha",
    "react": "^0.14.1",
    "react-dom": "^0.14.1"
```

**Comment by importre** [comment]
Really need all?
I know that the packages are included in `dist/photon.js`. (Actually [`react` and `react-dom` will not be included.](https://github.com/react-photonkit/react-photonkit/blob/master/webpack.config.js#L14-L17))

Anyway, I agree with you if my opinion is wrong.

**Comment by ragingwind** [comment]
:) I'm not sure. those of packages already was in there. I think all of packages should be in devDependencies

**Comment by importre** [comment]
then, go ahead as your idea :)

:train: =3=33

**Comment by ragingwind** [comment]
Closed as https://github.com/react-photonkit/react-photonkit/commit/56b5e325c70759628eb9dc6b942a2e3cb3a6698a

**Comment by importre** [comment]
:tulip:
