### ISSUE TITLE
Use with font awesome

### ISSUE THREAD

**Issue by rodryquintero** [react-photonkit/react-photonkit#27]
Please allow us to use font awesome icons with photon-kit.

[Font Awesome](http://fontawesome.io/icons/)

**Comment by ragingwind** [comment]
Would you give me more hints what is mean of using font awesome?

**Comment by rodryquintero** [comment]
Simple. Just make it possible to use [Font Awesome](http://fontawesome.io/) icon set in Photon apps.

**Comment by ragingwind** [comment]
Not simple. I have no idea why we should support Font Awesome even photonkit doesn't support it

**Comment by rodryquintero** [comment]
Because Font Awesome is one of the most popular (if not the most popular) font icons today. I think font awesome icons would complement Photon greatly.

**Comment by ragingwind** [comment]
I recommend that you propose the issue on photonkit with more detail requirement.

**Comment by rodryquintero** [comment]
I will when I get some time off to do a good write up.
