### ISSUE TITLE
Cleanup project files

### ISSUE THREAD

**Issue by ragingwind** [react-photonkit/react-photonkit#3]
- [x] config files, .npmignore, .gitignore editorconfigs
- [x] ~~fix naming styles~~
- [x] build files [optional]

**Comment by ragingwind** [comment]
@importre Using editorconfigs needs to be in the project for consistency of indent of the code. currently you're using space/2 that would be fine to be a default. see https://github.com/react-photonkit/react-photonkit/commit/0d06d6e8741f6b314195c8bf95f146a4ee831952

**Comment by importre** [comment]
nice work!
