### ISSUE TITLE
Not implemented features yet

### ISSUE THREAD

**Issue by importre** [react-photonkit/react-photonkit#7]
## TabGroup
- [ ] : `tab-item-fixed`
- [ ] : close a tab
## ListGroup
- [ ] : `list-group-header`
### Reference
- http://photonkit.com/components/

**Comment by ragingwind** [comment]
Close first and then make a new plan

**Comment by ragingwind** [comment]
Moved to https://github.com/react-photonkit/react-photonkit/issues/28
