### ISSUE TITLE
Remove release.js

### ISSUE THREAD

**Issue by ragingwind** [react-photonkit/react-photonkit#8]
It doesn't need to be in project. You can use node module installed on your system
- https://www.npmjs.com/package/publish-release
- https://www.npmjs.com/package/github-releases

**Comment by importre** [comment]
:ok_hand: remove it :)
and please choose the best one.

**Comment by ragingwind** [comment]
I have no taste of that. I always did it in manually

**Comment by ragingwind** [comment]
publish-release would be fine for this cases I think

**Comment by importre** [comment]
:grin:
